version: '3.9'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
      - arquivo.env
    depends_on:
      - postgres
    ports:
      - 80:80
    expose:
      - 80
      - 3000
      - 9229
    volumes:
      - ./public:/shopper/backend/public
      - ./src:/shopper/backend/src
      - ./package.json:/shopper/backend/package.json
      - /shopper/node_modules
    command: 'npm run start'

  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopper
    ports:
      - 5432:5432
    expose:
      - 5432
