version: '3.9'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
      - arquivo.env
    depends_on:
      - postgres
    ports:
      - 80:3000
    expose:
      - 80
      - 3000
    volumes:
      - .:/shopper/backend
      - /shopper/backend/node_modules
    command: 'npm run start:debug'

  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopper
    ports:
      - 5432:5432
    expose:
      - 5432
